language: node_js

node_js:
  - "0.10"
  - "0.12"
  - "4.0"

env:
  - CXX=g++-4.8 COVERAGE=true

script:
  - "make test"

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

branches:
  only:
    - master

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/db9084078a6ceda4fe03
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
